name: la persé 2
favicon: null
layout_spectrum: 0.214250574586913
typography_spectrum: 0.9160107423085719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5455365632660687
  lightness: 0.1980491739232093
  saturation: 0.8802305962890387
  rhythmicContrast: 0.39414818468503654
purpose: []
